// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDEeId5RItNv6M_qaRaM8na6c1s8-YJc8',
    appId: '1:554747694865:web:54bde3c95ef3d5baa306b0',
    messagingSenderId: '554747694865',
    projectId: 'tubes-market-hewan2',
    authDomain: 'tubes-market-hewan2.firebaseapp.com',
    storageBucket: 'tubes-market-hewan2.appspot.com',
    measurementId: 'G-6TT0QEP68R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjFn82IgwAzMfgH8opgAd2pPCtuekFXT4',
    appId: '1:554747694865:android:fd00375cbcb3c10fa306b0',
    messagingSenderId: '554747694865',
    projectId: 'tubes-market-hewan2',
    storageBucket: 'tubes-market-hewan2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADadZxDgIkPMFDa4N4u2_ePxpxOUZo1BE',
    appId: '1:554747694865:ios:92a3199ab33d382da306b0',
    messagingSenderId: '554747694865',
    projectId: 'tubes-market-hewan2',
    storageBucket: 'tubes-market-hewan2.appspot.com',
    iosBundleId: 'com.example.tubesMarketHewan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADadZxDgIkPMFDa4N4u2_ePxpxOUZo1BE',
    appId: '1:554747694865:ios:b1ebb84b6967b5d0a306b0',
    messagingSenderId: '554747694865',
    projectId: 'tubes-market-hewan2',
    storageBucket: 'tubes-market-hewan2.appspot.com',
    iosBundleId: 'com.example.tubesMarketHewan.RunnerTests',
  );
}
